services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    ports:
      - "5432:5432"
    env_file:
      - ./back-end/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app-network:
        ipv4_address: ${DB_HOST}

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
