services:
  backend:
    container_name: nest-backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env
    networks:
      - app-network

  frontend:
    container_name: vite-frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./front-end/.env
    volumes:
      - ./front-end:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    external: true
